spring: 
  profiles: 
    active: 
      - dev
--- 
server:  
 port:  8001

spring: 
  profiles: dev   #开发环境
  application:  
    name: microservicecloud-config-provider-client
    
mybatis: 
 config-location:  classpath:mybatis/mybatis.cfg.xml           # mybatis配置文件所在路径
 type-aliases-package:  com.microservicecloud.entities         # 所有entity别名类所在包
 mapper-locations: 
  - classpath:mapper/**/*.xml                       # mapper映射文件

spring: 
 application:  
  name:  microservicecloud-dept
 datasource: 
  type:  com.alibaba.druid.pool.DruidDataSource                # 当前数据源操作类型 
  driver-class-name:  org.gjt.mm.mysql.Driver                  # mysql驱动包
  url:  jdbc:mysql://localhost:3306/cloudDB01                    # 数据库名称
  username:  root
  password:  root
  dbcp2: 
   min-idle:  5                                               # 数据库连接池的最小维持连接数
   initial-size:  5                                           # 初始化连接数
   max-total:  5                                              # 最大连接数
   max-wait-millis:  200                                      # 等待连接获取的最大超时时间
   
eureka:          #客户端注册进eureka服务列表内
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka   #单机版注册
      defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id:  config-dept8001-dev    #自定义服务名称
    prefer-ip-address: true                     #访问显示IP访问地址

---  
server:  
 port:  8001

spring: 
  profiles: test   #测试环境
  application:  
    name: microservicecloud-config-provider-client
    
mybatis: 
 config-location:  classpath:mybatis/mybatis.cfg.xml           # mybatis配置文件所在路径
 type-aliases-package:  com.microservicecloud.entities         # 所有entity别名类所在包
 mapper-locations: 
  - classpath:mapper/**/*.xml                       # mapper映射文件

spring: 
 application:  
  name:  microservicecloud-dept
 datasource: 
  type:  com.alibaba.druid.pool.DruidDataSource                # 当前数据源操作类型 
  driver-class-name:  org.gjt.mm.mysql.Driver                  # mysql驱动包
  url:  jdbc:mysql://localhost:3306/cloudDB02                    # 数据库名称
  username:  root
  password:  root
  dbcp2: 
   min-idle:  5                                               # 数据库连接池的最小维持连接数
   initial-size:  5                                           # 初始化连接数
   max-total:  5                                              # 最大连接数
   max-wait-millis:  200                                      # 等待连接获取的最大超时时间
   
eureka:          #客户端注册进eureka服务列表内
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka   #单机版注册
      defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id:  config-dept8001-test    #自定义服务名称
    prefer-ip-address: true                     #访问显示IP访问地址

--- 
#请保持为UTF-8格式